
### Token

POST http://localhost:3000/api/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmZmRlNjI3LTljYjAtNDU0ZC04OTIwLThjZDY2M2RhNzAxZCIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3MzMzMzQ1NDQsImV4cCI6MTc2NDg3MDU0NH0.NWrhj_nhHxMlwDCcnT0vfbE2etSHQLvaPA7W4iA_4xE"
}

### Autentikaatio

POST http://localhost:3000/api/auth/request 
Content-Type: application/json

{
  "email": "hamalainen.don@gmail.com"
}

### Profiili

GET http://localhost:3000/api/user/profile
Content-Type: application/json
Authorization: Bearer <Token>
### 
PUT http://localhost:3000/api/user/profile
Content-Type: application/json
Authorization: Bearer <Token>

{
  "newUsername": "newusername"
  //"newPassword": "newpassword",
  //"currentPassword": "newpassword3"
}

### Ottelut
GET http://localhost:3000/api/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmZmRlNjI3LTljYjAtNDU0ZC04OTIwLThjZDY2M2RhNzAxZCIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3MzMzMzQ1NDQsImV4cCI6MTc2NDg3MDU0NH0.NWrhj_nhHxMlwDCcnT0vfbE2etSHQLvaPA7W4iA_4xE
Content-Type: application/json

###
POST http://localhost:3000/api/matches/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmZmRlNjI3LTljYjAtNDU0ZC04OTIwLThjZDY2M2RhNzAxZCIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3MzMzMzQ1NDQsImV4cCI6MTc2NDg3MDU0NH0.NWrhj_nhHxMlwDCcnT0vfbE2etSHQLvaPA7W4iA_4xE
Content-Type: application/json

{
  "match_name": "Arnak"
}

### 

DELETE http://localhost:3000/api/matches/113c05d9-b29f-4b06-8010-aec0036024a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhmZmRlNjI3LTljYjAtNDU0ZC04OTIwLThjZDY2M2RhNzAxZCIsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE3MzMzMzQ1NDQsImV4cCI6MTc2NDg3MDU0NH0.NWrhj_nhHxMlwDCcnT0vfbE2etSHQLvaPA7W4iA_4xE
Content-Type: application/json

### 

POST  http://localhost:3000/api/matches/join/258add13-e660-4559-af58-f39b640f0244
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5YmFjZDZjLTU1NzgtNDcxYi1hMTRkLTMyMjNkNDBlNDQzNiIsInVzZXJuYW1lIjoidGVzdHVzZXIyIiwiaWF0IjoxNzMzMzUyNzY5LCJleHAiOjE3NjQ4ODg3Njl9.yZejrGJx7o3hZIl48AL8sFOiWkm1ENPdOQ43oby-V4w
Content-Type: application/json